// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/JoeWright/workspace/try-ai/about-me-ai/node_modules/.pnpm/dumi@2.4.30_@babel+core@7.29.7_@rspack+core@2.0.8_@swc+helpers@0.5.23__@swc+helpers@0.5_e14079bf9a8d89cc4620d4cf478d42b9/node_modules/dumi/theme-default/slots/Header/index.js';
