// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/JoeWright/workspace/try-ai/about-me-ai/node_modules/.pnpm/dumi@2.4.30_@babel+core@7.29.7_@rspack+core@2.0.8_@swc+helpers@0.5.23__@swc+helpers@0.5_e14079bf9a8d89cc4620d4cf478d42b9/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/JoeWright/workspace/try-ai/about-me-ai/packages/floating-assistant/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/JoeWright/workspace/try-ai/about-me-ai/node_modules/.pnpm/dumi@2.4.30_@babel+core@7.29.7_@rspack+core@2.0.8_@swc+helpers@0.5.23__@swc+helpers@0.5_e14079bf9a8d89cc4620d4cf478d42b9/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/JoeWright/workspace/try-ai/about-me-ai/node_modules/.pnpm/dumi@2.4.30_@babel+core@7.29.7_@rspack+core@2.0.8_@swc+helpers@0.5.23__@swc+helpers@0.5_e14079bf9a8d89cc4620d4cf478d42b9/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
